config/routes.rb
Friendcircle::Application.routes.draw do

  get '/feed' => 'users#feed'

  resource :session, only: [:new, :create, :destroy]
  resource :user, only: [:new, :create, :show]
  resources :circles, except: [:index]
  resources :posts, only: [:new, :create, :show]

end

app/models/circle.rb
class Circle < ActiveRecord::Base
  attr_accessible :name, :user_id, :friend_ids

  belongs_to :user #as owner
  has_many :circleships
  has_many :friends, class_name: "User", through: :circleships
  has_many :post_shares
  has_many :posts, through: :post_shares

  validates :name, :user, presence: true
  validates :name, uniqueness: {scope: :user_id, case_sensitive: false}
end

app/models/circleship.rb
class Circleship < ActiveRecord::Base
  attr_accessible :circle_id, :user_id

  belongs_to :circle
  belongs_to :friend, foreign_key: :user_id, class_name: "User"

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :name, :post_id, :url

  belongs_to :post
  before_save :set_name

  validates :url, presence: true

  def set_name
    self.name = self.url if name.blank?
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :name, :user_id, :circle_ids, :links_attributes

  belongs_to :user
  has_many :links
  has_many :post_shares
  has_many :circles, through: :post_shares
  accepts_nested_attributes_for :links, :reject_if => :all_blank
end

app/models/post_share.rb
class PostShare < ActiveRecord::Base
  attr_accessible :circle_id, :post_id

  belongs_to :circle
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :session_token, :username, :password, :password_confirmation,
                  :posts_attributes
  has_secure_password

  has_many :circles #as owner
  has_many :circleships
  has_many :sectors, through: :circleships, source: :circle
  has_many :posts
  accepts_nested_attributes_for :posts, reject_if: :all_blank

  validates :username, :password, :password_confirmation, presence: true
  validates :username, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  def set_flash(message)
    flash[:notices] ||= []
    flash[:notices] << message
  end
end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController

  def new
    @circle = Circle.new
  end

  def create
    @circle = Circle.new(name: params[:circle][:name],
                         user_id: params[:circle][:user_id])
    ensure_current_user(@circle.user_id)
    if @circle.save
      @circle.update_attribute(:friend_ids, params[:circle][:friend_ids])
      redirect_to @circle
    else
      set_flash "#{@circle.errors.full_messages}"
      render :new
    end
  end

  def edit
    @circle = Circle.find(params[:id])
  end

  def update
    @circle = Circle.find(params[:id])
    ensure_current_user(@circle.user_id)
    if @circle.update_attributes(name: params[:circle][:name],
                         user_id: params[:circle][:user_id])
      @circle.update_attribute(:friend_ids, params[:circle][:friend_ids])
      redirect_to @circle
    else
      set_flash "#{@circle.errors.full_messages}"
      render :new
    end

  end

  def destroy
  end

  def show
    @circle = Circle.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post])
    ensure_current_user(@post.user_id)
    if @post.save
      redirect_to @post
    else
      set_flash "Could not save post"
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_username(params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      login @user
      redirect_to feed_url
    else
      set_flash "Invalid something or other in session."
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authorize, only: [:feed]

  def new
    @user = User.new
    @post = Post.new
  end

  def create
    @user = User.new(params[:user])
    if @user.password == @user.password_confirmation && @user.save
      login @user
      redirect_to feed_url
    else
      set_flash "Invalid something or other."
      @post = @user.posts.first
      render :new
    end
  end

  def feed
    @posts = current_user.sectors.map{ |s| s.posts }.flatten.uniq.reverse
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    token = SecureRandom::urlsafe_base64
    if user.update_attribute(:session_token, token)
      session[:session_token] = token
    else
      set_flash "#{user.errors.full_messages}"
    end
  end

  def logout
    current_user.update_attributes(session_token: nil)
    session[:session_token] = nil
  end

  def current_user
    if session[:session_token]
      @current_user ||= User.find_by_session_token(session[:session_token])
    end
  end

  def logged_in?
    !!current_user
  end

  def authorize
    unless logged_in?
      set_flash "Not authorized"
      redirect_to new_session_url
    end
  end

  def ensure_current_user(id)
    unless current_user.id == id
      logout
      set_flash "Stop hacking us!"
      redirect_to new_session_url
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/circles/_circle.html.erb
<ul>
<% circle.friends.each do |friend| %>
  <li><%= friend.username %></li>
<% end %>
</ul>

app/views/circles/_form.html.erb
<% if @circle.persisted? %>
<% action_name = circle_url(@circle.id) %>
<% post_value = "Update circle" %>
<% method_name = "put" %>
<% else %>
<% action_name = circles_url %>
<% post_value = "Create circle" %>
<% method_name = "post" %>
<% end %>
<form action="<%= action_name %>" method="post">
  <input type="hidden" name="authenticity_token"
         value="<%= form_authenticity_token %>">
  <label for="name">Circle Name</label>
  <input type="text" id="name" name="circle[name]" value="<%= @circle.name %>">

  <label>Add Friends</label>
  <% User.all.each do |user| %>
    <% next if user.username == current_user.username %>
    <label for="user<%= user.id %>"><%= user.username %></label>
    <input type="checkbox" id="user<%= user.id %>" name="circle[friend_ids][]"
           value ="<%= user.id %>"
           <%= "checked" if @circle.friends.include?(user) %> >
  <% end %>
  <input type="hidden" name="circle[user_id]" value="<%= current_user.id %>">
  <input type="hidden" name="circle[friend_ids][]" value="">

  <input type="hidden" name="_method" value="<%= method_name %>">

  <input type="submit" value="<%= post_value %>">
</form>

app/views/circles/create.html.erb
<h1>Circles#create</h1>
<p>Find me in app/views/circles/create.html.erb</p>

app/views/circles/destroy.html.erb
<h1>Circles#destroy</h1>
<p>Find me in app/views/circles/destroy.html.erb</p>

app/views/circles/edit.html.erb
<h1>Edit Circle <%= @circle.name %><h1>
<%= render partial: "form" %>

app/views/circles/new.html.erb
<h1>New Circle</h1>
<%= render partial: "form" %>

app/views/circles/show.html.erb
<h1><%= @circle.name %></h1>

  <%= render @circle %>

  <%= link_to "Edit Circle", edit_circle_url(@circle) %>

<ul>
  <%= render @circle.posts %>
</ul>

app/views/circles/update.html.erb
<h1>Circles#update</h1>
<p>Find me in app/views/circles/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Friendcircle</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <link href='http://fonts.googleapis.com/css?family=Noto+Sans:400,700' rel='stylesheet' type='text/css'>
  <% if flash[:notices]%>
    <% flash[:notices].each do |notice| %>
      <%= notice %>
    <% end %>
  <% end %>

<%= yield %>

<% if logged_in? %>
<form action="<%= session_url %>" method="post">
  <input type="hidden" name="authenticity_token"
            value="<%= form_authenticity_token %>" >
  <input type="hidden" name="_method" value="delete">
  <input type="submit" name="logout" value="Log Out">
</form>
<% end %>
</body>
</html>

app/views/posts/_form.html.erb
  <input type="hidden" name="authenticity_token"
         value="<%= form_authenticity_token %>">
  <label for="name">Post Title</label>
  <input type="text" name="<%= prefix %>[name]" value="<%= post.name %>">

  <label for="body">Body</label>
  <textarea name="<%= prefix %>[body]"><%= post.body %></textarea>

  <% if current_user %>
    <label>Circles</label>
    <% current_user.circles.each do |circle| %>
      <label for="circle<%= circle.id %>"><%= circle.name %></label>
      <input type="checkbox" id="circle<%= circle.id %>"
             name="<%= prefix %>[circle_ids][]"
             value="<%= circle.id %>"
             <%= "checked" if post.circles.include?(circle) %>>
    <% end %>
    <input type="hidden" name="<%= prefix %>[circle_ids][]" value="">

  <% end %>

  <label>Links</label>
  <% 3.times do |n| %>
  <label for="link_name<%= n %>">Name</label>
  <input type="text" name="<%= prefix %>[links_attributes][<%= n %>][name]"
         id="link_name<%= n %>">
  <label for="link_url<%= n %>">URL</label>
  <input type="url" name="<%= prefix %>[links_attributes][<%= n %>][url]">
  <% end %>

app/views/posts/_post.html.erb
<h2><%= post.name %></h2>
<h3>Author: <%= post.user.username %></h3>
<p><%= post.body %></p>

<ul>
  <% post.links.each do |link| %>
    <li><%= link_to link.name, link.url %></li>
  <% end %>
</ul>

app/views/posts/edit.html.erb
WE SHOULD IMPLEMENT THIS

app/views/posts/new.html.erb
<h1>NEW POST</h1>
<form action="<%= posts_url %>" method="post">
<%= render partial: "form", locals: { post: @post, prefix: "post" } %>
    <input type="hidden" name="<%= prefix %>[user_id]" value="<%= current_user.id %>">
  <input type="submit" value="Create Post">
</form>

app/views/posts/show.html.erb
<%= render @post %>

<h3>Circles shared with</h3>
<ul>
  <% @post.circles.each do |circle| %>
    <li><%= circle.name %></li>
  <% end %>
</ul>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/feed.html.erb
<h1>Feed.me</h1>

<%= render @posts %>

app/views/users/new.html.erb
<h1>Feed.me</h1>

<form action="<%= user_url %>" method="post">
  <input type="hidden" name="authenticity_token"
                   value="<%= form_authenticity_token %>">
  <label for="username">Username</label>
  <input type="text" id="username" name="user[username]">

  <label for="password">Password</label>
  <input type="password" id="password" name="user[password]">

  <label for="confirm_password">Confirm password</label>
  <input type="password" id="confirm_password" name="user[password_confirmation]">


  <h2> Make your first post now </h2>
<%= render partial: "posts/form", locals: { post: @post, prefix: "user[posts_attributes][0]" } %>

  <input type="submit" value="Sign Up">
</form>